apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: spiffworkflow-backend-claim1
    app.kubernetes.io/name: spiffworkflow-backend-claim1
  name: spiffworkflow-backend-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
