
groups:
  admin:
    users: [admin@reverencecare.com]
  group1:
    users: [jason@sartography.com, kevin@sartography.com]
  group2:
    users: [dan@sartography.com]

permissions:
  admin:
    groups: [admin, group1, group2]
    allowed_permissions: [create, read, update, delete]
    uri: /*
